openapi: 3.0.1
info:
  title: Microblog API
  description: API contract for Mini Social Media Platform (Microblog) — posts, follows, feed, search, notifications.
  version: 1.0.0
servers:
  - url: https://api.microblog.example.com/v1
    description: Production server
  - url: http://localhost:8080/v1
    description: Local dev
security:
  - bearerAuth: []
tags:
  - name: Auth
    description: Authentication and token management
  - name: Users
    description: User registration, profile
  - name: Posts
    description: Create/read/update posts
  - name: Feed
    description: Timeline and trending
  - name: Search
    description: Search posts and hashtags
  - name: Notifications
    description: User notifications
paths:
  /auth/register:
    post:
      tags: [Auth]
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
  /auth/login:
    post:
      tags: [Auth]
      summary: Login and receive access + refresh tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /auth/refresh:
    post:
      tags: [Auth]
      summary: Refresh access token using refresh token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
      responses:
        '200':
          description: New tokens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /users/{username}:
    get:
      tags: [Users]
      summary: Get public profile by username
      parameters:
        - $ref: '#/components/parameters/username'
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileResponse'
        '404':
          $ref: '#/components/responses/NotFound'
  /me:
    get:
      tags: [Users]
      summary: Get current authenticated user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Current user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
  /posts:
    post:
      tags: [Posts]
      summary: Create a new post
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePostRequest'
      responses:
        '201':
          description: Post created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponse'
    get:
      tags: [Posts]
      summary: Get posts (global) with pagination
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
      responses:
        '200':
          description: List of posts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostsListResponse'
  /posts/{postId}:
    get:
      tags: [Posts]
      summary: Get post by id
      parameters:
        - $ref: '#/components/parameters/postId'
      responses:
        '200':
          description: Post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponse'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags: [Posts]
      summary: Delete a post (owner only)
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/postId'
      responses:
        '204':
          description: Deleted
        '403':
          $ref: '#/components/responses/Forbidden'
  /posts/{postId}/like:
    post:
      tags: [Posts]
      summary: Like a post
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/postId'
      responses:
        '200':
          description: Liked
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LikeResponse'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags: [Posts]
      summary: Unlike a post
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/postId'
      responses:
        '204':
          description: Unliked
  /posts/{postId}/comments:
    post:
      tags: [Posts]
      summary: Add a comment to a post
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/postId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCommentRequest'
      responses:
        '201':
          description: Comment created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommentResponse'
    get:
      tags: [Posts]
      summary: List comments for a post
      parameters:
        - $ref: '#/components/parameters/postId'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
      responses:
        '200':
          description: Comments list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommentsListResponse'
  /comments/{commentId}/like:
    post:
      tags: [Posts]
      summary: Like a comment
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/commentId'
      responses:
        '200':
          description: Liked comment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LikeResponse'
  /follow/{username}:
    post:
      tags: [Users]
      summary: Follow a user
      security:
        - bearerAuth: []
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Followed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FollowResponse'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags: [Users]
      summary: Unfollow a user
      security:
        - bearerAuth: []
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Unfollowed
  /feed:
    get:
      tags: [Feed]
      summary: Get authenticated user's timeline
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
      responses:
        '200':
          description: Timeline
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeedResponse'
  /trending:
    get:
      tags: [Feed]
      summary: Get trending hashtags
      responses:
        '200':
          description: Trending list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Hashtag'
  /search:
    get:
      tags: [Search]
      summary: Search posts by keyword or hashtag
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResults'
  /notifications:
    get:
      tags: [Notifications]
      summary: Get current user's notifications
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
      responses:
        '200':
          description: Notifications
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationsList'
    post:
      tags: [Notifications]
      summary: Mark notifications as read (bulk)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: integer
      responses:
        '200':
          description: Updated
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    postId:
      name: postId
      in: path
      required: true
      schema:
        type: integer
    commentId:
      name: commentId
      in: path
      required: true
      schema:
        type: integer
    page:
      name: page
      in: query
      required: false
      schema:
        type: integer
        default: 0
    size:
      name: size
      in: query
      required: false
      schema:
        type: integer
        default: 20
    username:
      name: username
      in: path
      required: true
      schema:
        type: string
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
    RegisterRequest:
      type: object
      required: [username, email, password]
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
    LoginRequest:
      type: object
      required: [username, password]
      properties:
        username:
          type: string
        password:
          type: string
    RefreshRequest:
      type: object
      properties:
        refresh_token:
          type: string
    AuthResponse:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
        expires_in:
          type: integer
    UserResponse:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        email:
          type: string
        created_at:
          type: string
          format: date-time
    UserProfileResponse:
      allOf:
        - $ref: '#/components/schemas/UserResponse'
        - type: object
          properties:
            full_name:
              type: string
            bio:
              type: string
            avatar_url:
              type: string
            location:
              type: string
    CreatePostRequest:
      type: object
      required: [content]
      properties:
        content:
          type: string
        hashtags:
          type: array
          items:
            type: string
    PostResponse:
      type: object
      properties:
        id:
          type: integer
        user:
          $ref: '#/components/schemas/UserResponse'
        content:
          type: string
        created_at:
          type: string
          format: date-time
        like_count:
          type: integer
        comment_count:
          type: integer
        hashtags:
          type: array
          items:
            $ref: '#/components/schemas/Hashtag'
    PostsListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/PostResponse'
        page:
          type: integer
        size:
          type: integer
        total:
          type: integer
    CreateCommentRequest:
      type: object
      required: [content]
      properties:
        content:
          type: string
    CommentResponse:
      type: object
      properties:
        id:
          type: integer
        user:
          $ref: '#/components/schemas/UserResponse'
        content:
          type: string
        created_at:
          type: string
          format: date-time
        like_count:
          type: integer
    CommentsListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/CommentResponse'
        page:
          type: integer
        size:
          type: integer
        total:
          type: integer
    LikeResponse:
      type: object
      properties:
        post_id:
          type: integer
        user_id:
          type: integer
        like_count:
          type: integer
    FollowResponse:
      type: object
      properties:
        follower_id:
          type: integer
        following_id:
          type: integer
    FeedItem:
      type: object
      properties:
        post:
          $ref: '#/components/schemas/PostResponse'
        score:
          type: number
    FeedResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/FeedItem'
        page:
          type: integer
        size:
          type: integer
        total:
          type: integer
    Hashtag:
      type: object
      properties:
        id:
          type: integer
        tag:
          type: string
        count:
          type: integer
    SearchResults:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/PostResponse'
        page:
          type: integer
        size:
          type: integer
        total:
          type: integer
    Notification:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        type:
          type: string
        actor_id:
          type: integer
        post_id:
          type: integer
        created_at:
          type: string
          format: date-time
        is_read:
          type: boolean
    NotificationsList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Notification'
        page:
          type: integer
        size:
          type: integer
        total:
          type: integer
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
